### ISSUE TITLE
Changes related to list of tags

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1170]
1. Remove the list of tags from the home page and add it to the browse page.
2. Official list of tags:
https://docs.google.com/document/d/1Dhb4YQ-NRPqeTmFxeHkO9vNdhxql9oXFrOROodQiZIw/edit

List of official 9 Canonizer topic “Tags”

Politics
Religion and Philosophy
Organizations
Social Sciences and Economics
Hard Sciences
Entertainment
Relationships
History
Current Events

**Comment by sajid315** [comment]
@ks-rahul I pushed the updates required for topic tags listing, following is the PR that is merged on UX-dev server.

https://github.com/the-canonizer/canonizer-3.0-api/pull/1128

**Comment by rupalichavan9860** [comment]
Point 1 is not fixed. Remove the list of tags from the home page

**Comment by rupalichavan9860** [comment]
Verified

**Comment by rupalichavan9860** [comment]
Verified on live
