### ISSUE TITLE
On the Camp Statement History Comparison, camp statements are not displaying properly.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#118]
Please refer below screenshots : 
 I am comparing below statements : 
![image](https://user-images.githubusercontent.com/40416610/209048167-dbe67484-6dbf-4302-94e1-8e98c2202c5b.png)

Refer Camp Statement History Comparison : 
![image](https://user-images.githubusercontent.com/40416610/209048208-8fc58ceb-c789-4f39-bc19-e6beb4cfc69e.png)

**Comment by subhancd** [comment]
extra 1 is added when all statements are in bullet points
![image](https://user-images.githubusercontent.com/104552751/209065463-1ecc4acc-91d1-4609-a964-b8b99faf591b.png)

**Comment by sunilspr7** [comment]
@rupalichavan9860 I have tested this and its fixed in new editor (html editor)

**Comment by rupalichavan9860** [comment]
@sunilspr7 Still facing issue 

![image](https://user-images.githubusercontent.com/40416610/210593961-50688af7-28bd-43ae-b278-7e1056d29d46.png)

I am comparing below statements : 
![image](https://user-images.githubusercontent.com/40416610/210594184-0b279c4b-fa71-4db3-be27-e8e4491ac996.png)

**Comment by rupalichavan9860** [comment]
Not fixed

**Comment by SandeepTalentelgia** [comment]
Fixed

**Comment by rupalichavan9860** [comment]
@SandeepTalentelgia @sunilspr7 I am still facing format issue . Please refer below screenshot 

Removed contents are still displaying in comparison window

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/6e062669-4653-45ac-9d66-cd822821bd9b)

**Comment by rupalichavan9860** [comment]
Not working

**Comment by vikasranatalentelgia** [comment]
@rupalichavan9860 please check now

**Comment by rupalichavan9860** [comment]
Removed contents are highlighted

**Comment by rupalichavan9860** [comment]
Working fine on live
