### ISSUE TITLE
Update camp : Incorrect pop up of creating new camp 

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1499]
Please refer attached screenshot : 

![image](https://github.com/user-attachments/assets/0106f13a-a3e3-42eb-b6b4-2091d506c4f9)

**Comment by ks-rahul** [comment]
@rupalichavan9860 could you please explain more about this ticket...

**Comment by sunnyjindal** [comment]
@ks-rahul we need to remove this popup when we click on Create/Update Camp button. Also, the layout has bit of issues. See bullets.

**Comment by ks-rahul** [comment]
@sunnyjindal I am removing the popup, ui is already fixed.

**Comment by rupalichavan9860** [comment]
@ks-rahul Not fixed 
![image](https://github.com/user-attachments/assets/0aa5e0e0-d771-449c-ac1c-b3d8e100a6b5)

**Comment by rupalichavan9860** [comment]
Verified on UX server

**Comment by rupalichavan9860** [comment]
Verified on live
