### ISSUE TITLE
When the direct supporter changes the support order, the delegated user has the incorrect score and preference number.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#1567]
Please refer below topic and screenshot for more details : 
https://canonizer.com/topic/81-Mind-Experts/33-Jason-K-Resch 

![image](https://github.com/user-attachments/assets/96b36486-8359-461f-bd24-3e178922568e)

**Comment by shavetatalentelgia** [comment]
@rupalichavan9860 , @saniatg , Please let me know the expected result and steps to check this issue.

**Comment by shavetatalentelgia** [comment]
@akuks , Need to debug this issue on live.

**Comment by shavetatalentelgia** [comment]
@rupalichavan9860 , This issue is fixed on live server. Please verify.

**Comment by rupalichavan9860** [comment]
@shavetatalentelgia Not fixed . Please check below supported camps page 

![Image](https://github.com/user-attachments/assets/35418c6e-6029-45e2-bcee-68d0a15d5b02)

![Image](https://github.com/user-attachments/assets/c52292d9-159e-4527-9e8b-334cbfb4cf7a)

**Comment by shavetatalentelgia** [comment]
Following camps require debugging -- Scores/Support Order

https://canonizer.com/topic/81-Mind-Experts/27-Michael-Edward-Johnson
https://canonizer.com/topic/81-Mind-Experts/29-Deepak-Loomba
https://canonizer.com/topic/81-Mind-Experts/28-Joel-Frohlich
https://canonizer.com/topic/81-Mind-Experts/24-Graeme-E-Smith
https://canonizer.com/topic/81-Mind-Experts/30-Gregg-Henriques
https://canonizer.com/topic/81-Mind-Experts/6-Marvin-Minsky

**Comment by saniatg** [comment]
The score count is incorrect here for the above mentioned URL's by Shveta @sajid315  can you please this

**Comment by rupalichavan9860** [comment]
Verified on Live
