### ISSUE TITLE
Some links in camp statements are still redirected to the wrong URL

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#223]
Please refer topic below : 
https://canonizer.com/topic/6-Canonizer-Jobs/1-Agreement

Click on below highlighted link : 
![image](https://user-images.githubusercontent.com/40416610/225799395-3205d4d9-6f4e-46a5-b97f-d17684113698.png)

Actual Result : 
Link is redirecting to wrong URL : https://canonizer.com/topic.asp/105 

Please refer attached screenshot : 

![image](https://user-images.githubusercontent.com/40416610/225799545-b8345b4b-da80-4921-9098-2e377200d4ca.png)

**Comment by ashish76** [comment]
@rupalichavan9860 This issue has been fixed in ticket number #225, and once its PR is merged, this issue will also be resolved. Therefore, I will move this issue to the review in progress status.

**Comment by rupalichavan9860** [comment]
@ashish76 I checked this and it is now redirecting to the right URL, but I can still see "Page Not Found" for a few seconds before seeing the actual page.


![image](https://user-images.githubusercontent.com/40416610/229860163-c2606207-45de-4815-89d2-cd2cbc6f1517.png)

**Comment by hassaanCD** [comment]
@rupalichavan9860 "Page 404" error still occurred for few seconds



![Image](https://user-images.githubusercontent.com/120023458/231074435-01dba6d3-03c3-4fb9-9aa0-1cdd3e8d8b5c.png)


and then it lands on following link



![Image](https://user-images.githubusercontent.com/120023458/231074534-726ff21a-9b65-4cc3-b773-7bc1b556a021.png)


kindly confirm

**Comment by ks-rahul** [comment]
@hassaanCD the code is not deployed on production. please check this on the staging

**Comment by hassaanCD** [comment]
@ks-rahul when I click the link on staging 



![Image](https://user-images.githubusercontent.com/120023458/231080951-c41b84d9-4242-4828-b8b3-2f7fa1414cd8.png)


it is redirecting me to "https://canonizer.com/topic/105/1" with page not found error



![Image](https://user-images.githubusercontent.com/120023458/231081204-db3a4255-af70-47f5-8adb-7a4e87e6ed81.png)


and the lands on this page



![Image](https://user-images.githubusercontent.com/120023458/231081449-b40877fa-fc32-4de0-8e99-c3926fb1db58.png)

**Comment by rupalichavan9860** [comment]
Working fine on staging and live

**Comment by rupalichavan9860** [comment]
Verified on live
