### ISSUE TITLE
Direct Supporter the time the change was submitted is unable to Agree and Object the submitted change in below case

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#232]
Steps to reproduce : 

1. Login with User A (Rupali C) and create topic(User A is supporter of Agreement camp)

![image](https://user-images.githubusercontent.com/40416610/227536369-ff78380f-43d5-48c0-8383-0c84c3e1abe4.png)

2. Login with User B(Rupali Cano) and add camp statement for Agreement camp

![image](https://user-images.githubusercontent.com/40416610/227536615-70ed3c15-0010-4a23-a5dc-c7d0d963835c.png)

3. Login with User A (Rupali C) and go to camp statement history : Can see Agree and Object 

![image](https://user-images.githubusercontent.com/40416610/227536993-a5b0a3a8-8d25-41eb-920e-6a231501ec17.png)

4. Remove support from Agreement camp : User A login(Rupali C) and Observe camp statement history page for in review record

Expected Result :Since the change was submitted when Rupali C was a supporter at the time, User A:Rupali C must be able to agree and object to it.

Actual Result : 
![image](https://user-images.githubusercontent.com/40416610/227538076-bf5a779a-3d37-4c35-8cad-83b04de87985.png)

After removing support 

![image](https://user-images.githubusercontent.com/40416610/227538235-651f45a7-0c30-4dfe-84d3-4b921a07130b.png)

**Comment by array-junkie** [comment]
@rupalichavan9860 What is the acceptance criteria for this ticket?

**Comment by array-junkie** [comment]
Acceptance Criteria By @rupalichavan9860 : https://docs.google.com/spreadsheets/d/1S_duROTix36r2nR2mQv0bDQ5VcRsnY_WRyOL2ZipFW8/edit#gid=840770996

**Comment by array-junkie** [comment]
@rupalichavan9860 There is 1 case to discuss.

"Given : User A is a direct supporter of the camp
And : User B(Supporter or non supporter) submitted(not committed) a change to the camp
When : User A removed support from camp
And: User B committed that change to the camp

Should User A have ability to agree & object?

**Comment by rupalichavan9860** [comment]
@BrentAllsop Could you please check and let me know what you think?

**Comment by BrentAllsop** [comment]
Until something is committed, it is as if it never happened, not entered into history, nobody ever sees it.
So if user A supports something when it is not yet committed, and removes their support, before it is committed, then it is like they were not a supporter when it actually happened and was recorded in history.  (And there is no way for user A to know of something, until it is committed.)  So, no, they should not have the right to object, since they were not a supporter, when it actually happened (recorded into history.)

**Comment by array-junkie** [comment]
Hi @BrentAllsop! Regarding this ticket and the last comment. It occurs to me that when a user submits a change we show submit(not committed) time on the card. And when the user hit the commit button, it just set the grace_period bit from 1 to 0. So in the last comment, it is stated that unless the user hit the commit button, the change will not be recorded in the history, and all the supporters at the time of commit will have the ability to agree & object. So when a user hit a commit button, what will be the effect? Do we have to update the submit time to commit the time, and it will also update the go-live time according to the submit & commit time?

**Comment by array-junkie** [comment]
PR has been raised from backend

https://github.com/the-canonizer/canonizer-3.0-api/pull/633
https://github.com/the-canonizer/canonizer-service/pull/213

**Comment by rupalichavan9860** [comment]
Given : User A is a direct supporter of the camp
And : User B(Supporter or non supporter) submitted(not committed) a change to the camp
When : User A removed support from camp
And: User B committed that change to the camp

In this case record should go live 

Actual Result : Record is still in "in review" with message "1 out of 1 required supporters have agreed"

**Comment by array-junkie** [comment]
It is fixed in PR [#673](https://github.com/the-canonizer/canonizer-3.0-api/pull/673)

**Comment by rupalichavan9860** [comment]
@M-Darab Please refer below steps : 
1. Login with User A (Rupali C) and create topic(User A is supporter of Agreement camp)
2. Login with User B(Rupali Cano) and add camp statement for Agreement camp
3. Login with User A (Rupali C) and go to camp statement history : Can see Agree and Object
4. Remove support from Agreement camp : User A login(Rupali C) and try to object

Expected Result :Since the change was submitted when Rupali C was a supporter at the time, User A:Rupali C must be able to agree and object to it.

Actual Result :  User is able to agree the changes and can see object button but Getting error "You are not authorized to object to this statement because you do not support this camp." on objection page
Refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/0664eb76-784e-46fb-9227-fcfe99aa36ad)

**Comment by array-junkie** [comment]
@rupalichavan9860  above mentioned issues are fixed now and PR has been raised. Have a look please after code merge
PR [#692](https://github.com/the-canonizer/canonizer-3.0-api/pull/692)

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by rupalichavan9860** [comment]
@M-Darab Last commented issue is still exists

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/5a5a36b6-bab5-4f76-a9a3-047acdc9a81e)

**Comment by array-junkie** [comment]
PR Raised https://github.com/the-canonizer/canonizer-3.0-api/pull/780

**Comment by rupalichavan9860** [comment]
Working fine on development server

**Comment by rupalichavan9860** [comment]
Working fine on live
