### ISSUE TITLE
Canonizer Admin : When a user submits a change to a topic or camp, the total number of Live Topics and Live Camps counts increase.

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#429]

**Comment by sajid315** [comment]
@rupalichavan9860 count stats issue has been resolved, you can have a look now.

**Comment by rupalichavan9860** [comment]
@sajid315 Still facing same issue. Can you please check again

**Comment by rupalichavan9860** [comment]
This is working fine now

**Comment by subhancd** [comment]
verified
