### ISSUE TITLE
profile picture should be changed without user having to remove his old picture first

### ISSUE THREAD

**Issue by subhancd** [the-canonizer/Canonizer-Beta--Issue-Tracking#708]
1. system should crop image rather than asking user to upload 1000x1000 image
2. user should be able to change his profile picture without having to remove it first
3. add an edit button for user to change the image
4. display appropriate error message when user uploads a pdf or gif etc
5. gif shouldn't be allowed

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/104552751/8a1be2ee-22ff-45a4-9c30-f1c27fb3de3f)

**Comment by akashgit77** [comment]
@sajid315 can we put "edit" & "delete" button bellow the profile picture.And only "view button" should be over the image?

**Comment by sajid315** [comment]
@wahaj-hafeez we need to introduce the update of image without deletion from front-end side, for that i have pushed the required changes from back-end side.

**Comment by DevAlchemyCD** [comment]
pr raised : https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1455

**Comment by saniatg** [comment]
@wahaj-hafeez this point is still not fixed as mentioned above
1. system should crop image rather than asking user to upload 1000x1000 image

![Screenshot 2024-01-25 at 1 37 09 AM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/a5d46c45-445b-4c0f-bff2-3f379889cc33)

**Comment by hassaanCD** [comment]
Verified on development server

**Comment by saniatg** [comment]
@wahaj-hafeez this point is still not fixed 

system should crop image rather than asking user to upload 1000x1000 image
![Screenshot 2024-02-21 at 5 10 23 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/504b6410-f58f-4b2e-9cf0-85aafb43a7fb)
