### ISSUE TITLE
Notification- showing invalid date when click on ' create thread notification'

### ISSUE THREAD

**Issue by saniatg** [the-canonizer/Canonizer-Beta--Issue-Tracking#721]
When click on notification which shows create thread. On click shows invalid date
![Screenshot 2023-12-28 at 3 05 07 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/956f61a5-1798-4b8c-8daf-b079c898fb37)
![Screenshot 2023-12-28 at 3 04 59 PM](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/91254708/338bc707-dd84-4220-864d-f1d83099a239)

**Comment by akashgit77** [comment]
@shahab-ramzan I am getting logged out, after clicking on "created thread notification".

**Comment by rupalichavan9860** [comment]
Yes user is getting logged out

**Comment by sajid315** [comment]
@rupalichavan9860 the issue of invalid date on click of notification is fixed. And also issue of auto logout is fixed from front-end as well. Can you please re-verify the changes on development server.

**Comment by rupalichavan9860** [comment]
@sajid315 We are still facing this issue for few seconds and then it is working fine 
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/946956ce-b564-4ccf-a27d-a3813a09d372)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1594

**Comment by rupalichavan9860** [comment]
Not fixed
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/04e5789c-c98a-47a5-ac87-d84b308adf09)

**Comment by DevAlchemyCD** [comment]
PR: https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1665

**Comment by sajid315** [comment]
@rupalichavan9860 issue related to "Invalid Date" on create camp thread is resolved now. You can have a look into this on development server.


![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/111273633/f98d2440-dffc-4cb1-9102-4de2af4f0c85)

**Comment by saniatg** [comment]
working fine on development
