### ISSUE TITLE
Admin (Shares) : Behavioral issue

### ISSUE THREAD

**Issue by rupalichavan9860** [the-canonizer/Canonizer-Beta--Issue-Tracking#840]
Steps to reproduce : 

1. Go to https://admin.canonizer.com/ 
2. Login with valid email and password
3. Go to Shares
4. Click on any nick name

Result :  User supports/profile page is opening in new tab 

5. Change month from drop down 
6. Click on any nick name

Result :  User supports/profile page is opening in same tab 

Expected Result : For consistency, both should behave the same way.

**Comment by rupalichavan9860** [comment]
Now page is opening in new tab but getting below error 

![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/93c77ace-273e-4849-a94d-f6b3544dd43d)

**Comment by sajid315** [comment]
@rupalichavan9860 URL issue is resolved and fixing has been pushed for both dev and prod admin panels. 

This issue is actually occured when we changed namespace term to canon.
And we also have to do fixing of the getting namespace from older URL's , E.g: 
https://canonizer.com/user/supports/595?namespace=1

When you will hit this URL its getting multiple API calls and getting the namespace as "**undefined**".

Might be @ks-rahul worked on it.

**Comment by rupalichavan9860** [comment]
https://development.canonizer.com/user/supports/595?namespace=1 This is working fine but still facing issue for https://canonizer.com/user/supports/595?namespace=1
