### ISSUE TITLE
It is showing "two agreement support" when we "sign" and then "directly join and support".

### ISSUE THREAD

**Issue by akashgit77** [the-canonizer/Canonizer-Beta--Issue-Tracking#988]
Steps:

1. First "Sign" agreement camp after that "Directly Join Support" .

![Image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/105647543/c80f2a06-1272-461f-93ab-6b898fe90811)

**Comment by rupalichavan9860** [comment]
@akashgit77 Yes same facing for sub camps :
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/27b4abf2-a063-479e-adeb-ed0dd3107351)

score is also incorrect

**Comment by array-junkie** [comment]
@rupalichavan9860 & @akashgit77 This is fixed in the following PR https://github.com/the-canonizer/canonizer-3.0-frontend/pull/1788
Moving it to in review

**Comment by rupalichavan9860** [comment]
@M-Darab Not fixed 
![image](https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/assets/40416610/ed46b5f5-60c6-4e50-aafe-63a2bc4071a1)

**Comment by rupalichavan9860** [comment]
Verified on development server

**Comment by saniatg** [comment]
working fine on live
